<link href="hoja_de_estilo.css" type="text/css" rel="stylesheet">

<body background="body2.jpg">

<?php
require_once 'PHPExcel.php';
$objPHPExcel = new PHPExcel();
// Set properties
$objPHPExcel->getProperties()->setCreator("ThinkPHP")
				->setLastModifiedBy("Motos")
				->setTitle("Office 2007 XLSX Test Document")
				->setSubject("Office 2007 XLSX Test Document")
				->setDescription("Test doc for Office 2007 XLSX, generated by PHPExcel.")
				->setKeywords("office 2007 openxml php")
				->setCategory("Inventarios");
$objPHPExcel->getActiveSheet()->setTitle('Inventarios Productos');

require_once("manejomysql.php");
conectar_bd();

$usuario_consulta = mysql_query("SELECT codigo_producto,nombre_producto, nombre_chino, nombre_ingles, stock, stock_minimo, unidad FROM producto order by nombre_producto;" );

if (mysql_num_rows($usuario_consulta) != 0)
{	
	$objPHPExcel->setActiveSheetIndex(0)
            ->setCellValue('A1', 'Codigo')
            ->setCellValue('B1', 'Detalle')
			->setCellValue('C1', 'QTY')
            ->setCellValue('D1', 'UNIT');
			
	for ( $i=0; $i< cuantos_registros_bd($usuario_consulta); $i++)
	{
		$registro= sacar_registro_bd($usuario_consulta);
				$j = $i + 2;
				$objPHPExcel->setActiveSheetIndex(0)
					->setCellValue('A'.$j, $registro['codigo_producto'])
					->setCellValue('B'.$j, $registro['nombre_producto'])
					->setCellValue('C'.$j, $registro['stock'])
					->setCellValue('D'.$j, $registro['unidad']);

	}
	
			
}
else
{

			$objPHPExcel->setActiveSheetIndex(0)
            ->setCellValue('A1', 'No hay registros de productos que cumplan con el requerimiento');

}



//setCellValueByColumnAndRow($column, $row, $value);

require_once 'PHPExcel/IOFactory.php';
$objWriter = PHPExcel_IOFactory::createWriter($objPHPExcel, 'Excel2007');
// Si queremos crear un PDF
//$objWriter = PHPExcel_IOFactory::createWriter($objPHPExcel, 'PDF');
$objWriter->save('reportes/inventarios.xlsx');

?>

<p align="center">EL REPORTE FUE CREADO Y GUARDADO, ESTE PUEDE SER ENCONTRADO "REPORTES\inventarios.xls"</a></p>
<br>
<p align="center"><a href="reportes/inventarios.xlsx">DESCARGAR REPORTE</a></p>
<br>
<p align="center"><a href="principal_target.php">VOLVER A LA PAGINA PRINCIPAL</a></p>

</body>
</html>

