<?php
require_once 'PHPExcel.php';
$objPHPExcel = new PHPExcel();
// Set properties
$objPHPExcel->getProperties()->setCreator("ThinkPHP")
				->setLastModifiedBy("Daniel Schlichtholz")
				->setTitle("Office 2007 XLSX Test Document")
				->setSubject("Office 2007 XLSX Test Document")
				->setDescription("Test doc for Office 2007 XLSX, generated by PHPExcel.")
				->setKeywords("office 2007 openxml php")
				->setCategory("Test result file");
$objPHPExcel->getActiveSheet()->setTitle('Minimalistic demo');


$objPHPExcel->setActiveSheetIndex(0)
            ->setCellValue('A1', 'update')
            ->setCellValue('B1', 'world!')
			->setCellValue('C3', 'Hello')
            ->setCellValue('A2', 'world!');

//setCellValueByColumnAndRow($column, $row, $value);

require_once 'PHPExcel/IOFactory.php';
$objWriter = PHPExcel_IOFactory::createWriter($objPHPExcel, 'Excel2007');
// Si queremos crear un PDF
//$objWriter = PHPExcel_IOFactory::createWriter($objPHPExcel, 'PDF');
$objWriter->save('myexcel.xlsx');



?>
